var searchData=
[
  ['o_0',['Stream I/O',['../codeExamples.html#sStreamIO',1,'']]],
  ['octree_20or_20n_20tree_1',['Is OpenVDB merely a generalized octree or N-tree?',['../faq.html#sGeneralizedOctree',1,'']]],
  ['of_20different_20types_2',['Processing grids of different types',['../houdini.html#sProcessingTypedGrids',1,'']]],
  ['of_20grid_20values_3',['Interpolation of grid values',['../codeExamples.html#sInterpolation',1,'']]],
  ['of_20nanovdb_4',['Overview of the directory tree of NanoVDB.',['../NanoVDB_SourceTree.html#autotoc_md4',1,'']]],
  ['of_20openvdb_5',['Can I customize the configuration of OpenVDB?',['../faq.html#sCustomizeVDB',1,'']]],
  ['of_20the_20directory_20tree_20of_20nanovdb_6',['Overview of the directory tree of NanoVDB.',['../NanoVDB_SourceTree.html#autotoc_md4',1,'']]],
  ['on_20the_20cpu_20and_20gpu_7',['Read a NanoVDB grid and access it on the CPU and GPU',['../NanoVDB_HelloWorld.html#autotoc_md10',1,'']]],
  ['on_20the_20grid_8',['Why are there no coordinate-based access methods on the grid?',['../faq.html#sAccessor',1,'']]],
  ['only_9',['Read a NanoVDB grid from a file (host only)',['../NanoVDB_HelloWorld.html#autotoc_md9',1,'']]],
  ['openvdb_10',['OpenVDB',['../codeExamples.html#sHelloWorld',1,'&ldquo;Hello, World&rdquo; for OpenVDB'],['../build.html',1,'Building OpenVDB'],['../build.html#buildUsingOpenVDB',1,'Building With OpenVDB'],['../faq.html#sCustomizeVDB',1,'Can I customize the configuration of OpenVDB?'],['../faq.html#sVoxel',1,'How are voxels represented in OpenVDB?'],['../faq.html#sContribute',1,'How can I contribute to OpenVDB?'],['../faq.html#sWhatCLA',1,'Is there a Contributor License Agreement for OpenVDB?'],['../index.html',1,'OpenVDB'],['../overview.html#simdInOpenVDB',1,'SIMD in OpenVDB'],['../transformsAndMaps.html#sTransforms',1,'Transforms in OpenVDB'],['../faq.html#sWhatIsVDB',1,'What is OpenVDB?'],['../faq.html#sVersionNumbering',1,'What is the version numbering system for OpenVDB?'],['../faq.html#sWhyUseVDB',1,'Why should I use OpenVDB?']]],
  ['openvdb_20an_20adaptive_20grid_11',['Is OpenVDB an adaptive grid?',['../faq.html#sAdaptiveGrid',1,'']]],
  ['openvdb_20ax_12',['OpenVDB AX',['../openvdbax.html',1,'index']]],
  ['openvdb_20ax_20repository_13',['OpenVDB AX Repository',['../axcplusplus.html#vdbaxrepo',1,'']]],
  ['openvdb_20ax_20types_14',['OpenVDB / OpenVDB AX Types',['../axcplusplus.html#vdbaxtoaxtypes',1,'']]],
  ['openvdb_20build_20artifacts_15',['Detected VCPKG toolchain is using a mismatching triplet for OpenVDB build artifacts',['../build.html#troubleshoot4',1,'']]],
  ['openvdb_20compare_20to_20existing_20sparse_20data_20structures_16',['How does OpenVDB compare to existing sparse data structures?',['../faq.html#sCompareVDB',1,'']]],
  ['openvdb_20components_17',['OpenVDB Components',['../dependencies.html#depComponents',1,'OpenVDB Components'],['../build.html#buildComponents',1,'OpenVDB Components']]],
  ['openvdb_20cookbook_18',['OpenVDB Cookbook',['../codeExamples.html',1,'']]],
  ['openvdb_20core_19',['OpenVDB core',['../NanoVDB_HowToBuild.html#autotoc_md5',1,'First example: building NanoVDB and OpenVDB core'],['../NanoVDB_HowToBuild.html#autotoc_md7',1,'Third example: build 'everything' in NanoVDB along with OpenVDB core']]],
  ['openvdb_20distributed_20under_20',['What license is OpenVDB distributed under?',['../faq.html#sWhatLicense',1,'']]],
  ['openvdb_20execution_20context_21',['OpenVDB Execution Context',['../ax.html#axexecutionxcontext',1,'']]],
  ['openvdb_20grid_20to_20nanovdb_20and_20use_20accessors_22',['Convert an OpenVDB grid to NanoVDB and use accessors',['../NanoVDB_HelloWorld.html#autotoc_md8',1,'']]],
  ['openvdb_20merely_20a_20generalized_20octree_20or_20n_20tree_23',['Is OpenVDB merely a generalized octree or N-tree?',['../faq.html#sGeneralizedOctree',1,'']]],
  ['openvdb_20openvdb_20ax_20types_24',['OpenVDB / OpenVDB AX Types',['../axcplusplus.html#vdbaxtoaxtypes',1,'']]],
  ['openvdb_20overview_25',['OpenVDB Overview',['../overview.html',1,'index']]],
  ['openvdb_20points_26',['OpenVDB Points',['../codeExamples.html#sPointsHelloWorld',1,'&ldquo;Hello, World&rdquo; for OpenVDB Points'],['../points.html',1,'OpenVDB Points']]],
  ['openvdb_20primarily_20for_20level_20set_20applications_27',['Is OpenVDB primarily for level set applications?',['../faq.html#sLevelSet',1,'']]],
  ['openvdb_20python_28',['OpenVDB Python',['../python.html',1,'index']]],
  ['openvdb_20replace_20dense_20grids_29',['Does OpenVDB replace dense grids?',['../faq.html#sReplaceDense',1,'']]],
  ['openvdb_20sop_20construction_30',['OpenVDB SOP construction',['../houdini.html#sOpenVDBOperators',1,'']]],
  ['openvdb_20store_20values_31',['How and where does OpenVDB store values?',['../faq.html#sValue',1,'']]],
  ['openvdb_20thread_20safe_32',['Is OpenVDB thread-safe?',['../faq.html#sThreadSafe',1,'']]],
  ['openvdb_20transforms_33',['Maps in OpenVDB Transforms',['../transformsAndMaps.html#sMaps',1,'']]],
  ['openvdb_20unbounded_34',['Is OpenVDB unbounded?',['../faq.html#sMaxRes',1,'']]],
  ['operations_35',['Maps and Mathematical Operations',['../transformsAndMaps.html#sGradientAndMaps',1,'']]],
  ['operations_36',['operations',['../codeExamples.html#sCompTools',1,'Compositing operations'],['../codeExamples.html#sCsgTools',1,'Level set CSG operations']]],
  ['operator_20construction_37',['General operator construction',['../houdini.html#sUIConstruction',1,'']]],
  ['operator_20precedence_38',['Operator Precedence',['../ax.html#axopprecedence',1,'']]],
  ['operators_39',['Operators',['../ax.html#axopbinary',1,'Binary Operators'],['../ax.html#axoperators',1,'Operators'],['../ax.html#axopunary',1,'Unary Operators']]],
  ['opfactory_40',['OpFactory',['../houdini.html#sOpFactory',1,'']]],
  ['or_20n_20tree_41',['Is OpenVDB merely a generalized octree or N-tree?',['../faq.html#sGeneralizedOctree',1,'']]],
  ['other_42',['Other',['../ax.html#axopother',1,'']]],
  ['over_20grids_43',['Iterating over grids',['../houdini.html#sIteratingOverGrids',1,'']]],
  ['overview_44',['Overview',['../overview.html',1,'OpenVDB Overview'],['../openvdbax.html#axoverview',1,'Overview']]],
  ['overview_20of_20the_20directory_20tree_20of_20nanovdb_45',['Overview of the directory tree of NanoVDB.',['../NanoVDB_SourceTree.html#autotoc_md4',1,'']]]
];
