var searchData=
[
  ['value_0',['What is the background value?',['../faq.html#sBackground',1,'']]],
  ['value_20accessor_1',['Value Accessor',['../overview.html#subsecValueAccessor',1,'']]],
  ['value_20for_20the_20windows_20crt_20with_20target_20build_20artifacts_2',['Unexpected value for the Windows CRT with target build artifacts.',['../build.html#troubleshoot5',1,'']]],
  ['value_20iterator_3',['Value Iterator',['../codeExamples.html#sValueIterator',1,'']]],
  ['value_20transformation_4',['Value transformation',['../codeExamples.html#sValueXformTools',1,'']]],
  ['values_5',['Values',['../points.html#secPtActiveValues',1,'Active Values'],['../points.html#secPtBackground',1,'Background and Tile Values'],['../codingStyle.html#sEnumerationValues',1,'Enumeration Values'],['../overview.html#subsecValues',1,'Tile, Voxel, and Background Values'],['../points.html#secPtSparsity',1,'Voxel Values']]],
  ['values_6',['values',['../faq.html#sValue',1,'How and where does OpenVDB store values?'],['../codeExamples.html#sInterpolation',1,'Interpolation of grid values'],['../codeExamples.html#sPopulatingGrids',1,'Populating a grid with values'],['../faq.html#sState',1,'What are active and inactive values?']]],
  ['values_20and_20voxels_7',['Sparse Values and Voxels',['../overview.html#secSparsity',1,'']]],
  ['variable_20identifiers_8',['Variable Identifiers',['../ax.html#axvaridentifiers',1,'']]],
  ['variables_9',['Variables',['../codingStyle.html#sClassInstanceVariables',1,'Class Instance Variables'],['../codingStyle.html#sClassStaticVariables',1,'Class Static Variables'],['../codingStyle.html#sGlobalVariables',1,'Global Variables']]],
  ['variables_20and_20arguments_10',['Local Variables and Arguments',['../codingStyle.html#sLocalVariablesAndArguments',1,'']]],
  ['vcpkg_11',['Building Dependencies using VCPKG',['../build.html#buildVCPKG',1,'']]],
  ['vcpkg_20toolchain_20is_20using_20a_20mismatching_20triplet_20for_20openvdb_20build_20artifacts_12',['Detected VCPKG toolchain is using a mismatching triplet for OpenVDB build artifacts',['../build.html#troubleshoot4',1,'']]],
  ['vdb_20stand_20for_13',['What does &quot;VDB&quot; stand for?',['../faq.html#sMeaningOfVDB',1,'']]],
  ['vectors_20matrices_14',['Vectors / Matrices',['../ax.html#axvecmats',1,'']]],
  ['velocity_20grids_15',['Staggered Velocity Grids',['../transformsAndMaps.html#sStaggered',1,'']]],
  ['velocity_20update_16',['Velocity Update',['../axexamples.html#axexamplevolumevel',1,'']]],
  ['version_20numbering_20system_20for_20openvdb_17',['What is the version numbering system for OpenVDB?',['../faq.html#sVersionNumbering',1,'']]],
  ['version_3a_18',['CMake Error ... Could NOT find XXX (Found unsuitable version: ... )',['../build.html#troubleshoot2',1,'']]],
  ['versioning_20api_20and_20abi_19',['Versioning, API and ABI',['../axcplusplus.html#vdbaxapiabi',1,'']]],
  ['vertex_20centered_20transforms_20',['Cell-Centered vs. Vertex-Centered Transforms',['../transformsAndMaps.html#sCellVsVertex',1,'']]],
  ['vex_20support_21',['AX VEX Support',['../ax.html#axvexsupport',1,'']]],
  ['volume_20clamping_22',['Volume Clamping',['../axexamples.html#axexamplevolumeclamp',1,'']]],
  ['volume_20examples_23',['Volume Examples',['../axexamples.html#axexamplevolumes',1,'']]],
  ['voxel_20access_24',['Voxel access',['../python.html#sPyAccessors',1,'']]],
  ['voxel_20and_20background_20values_25',['Tile, Voxel, and Background Values',['../overview.html#subsecValues',1,'']]],
  ['voxel_20interpretations_26',['Voxel Interpretations',['../transformsAndMaps.html#sVoxels',1,'']]],
  ['voxel_20space_20index_20space_20world_20space_27',['Voxel Space, Index Space, World Space',['../points.html#secPtSpaceAndTrans',1,'']]],
  ['voxel_20values_28',['Voxel Values',['../points.html#secPtSparsity',1,'']]],
  ['voxels_29',['Voxels',['../overview.html#subsecInactive',1,'Active and Inactive Voxels'],['../overview.html#secSparsity',1,'Sparse Values and Voxels']]],
  ['voxels_20represented_20in_20openvdb_30',['How are voxels represented in OpenVDB?',['../faq.html#sVoxel',1,'']]],
  ['vs_20attributehandle_31',['TypedAttributeArray vs AttributeHandle',['../points.html#secPtAttributePerformance',1,'']]],
  ['vs_20vertex_20centered_20transforms_32',['Cell-Centered vs. Vertex-Centered Transforms',['../transformsAndMaps.html#sCellVsVertex',1,'']]]
];
