var searchData=
[
  ['a_20contributor_20license_20agreement_20for_20openvdb_0',['Is there a Contributor License Agreement for OpenVDB?',['../faq.html#sWhatCLA',1,'']]],
  ['a_20custom_20deformer_1',['Moving Points with a Custom Deformer',['../codeExamples.html#sPointCustomDeformer',1,'']]],
  ['a_20file_20host_20only_2',['Read a NanoVDB grid from a file (host only)',['../NanoVDB_HelloWorld.html#autotoc_md9',1,'']]],
  ['a_20generalized_20octree_20or_20n_20tree_3',['Is OpenVDB merely a generalized octree or N-tree?',['../faq.html#sGeneralizedOctree',1,'']]],
  ['a_20grid_4',['a grid',['../codeExamples.html#sAllocatingGrids',1,'Creating and writing a grid'],['../codeExamples.html#sModifyingGrids',1,'Reading and modifying a grid']]],
  ['a_20grid_20with_20values_5',['Populating a grid with values',['../codeExamples.html#sPopulatingGrids',1,'']]],
  ['a_20mismatching_20triplet_20for_20openvdb_20build_20artifacts_6',['Detected VCPKG toolchain is using a mismatching triplet for OpenVDB build artifacts',['../build.html#troubleshoot4',1,'']]],
  ['a_20nanovdb_20grid_20and_20access_20it_20on_20the_20cpu_20and_20gpu_7',['Read a NanoVDB grid and access it on the CPU and GPU',['../NanoVDB_HelloWorld.html#autotoc_md10',1,'']]],
  ['a_20nanovdb_20grid_20from_20a_20file_20host_20only_8',['Read a NanoVDB grid from a file (host only)',['../NanoVDB_HelloWorld.html#autotoc_md9',1,'']]],
  ['a_20program_20example_9',['A Program Example',['../ax.html#axprogramexample',1,'']]],
  ['abi_10',['Versioning, API and ABI',['../axcplusplus.html#vdbaxapiabi',1,'']]],
  ['access_11',['Access',['../ax.html#axattribaccess',1,'Attribute Access'],['../ax.html#axopaccess',1,'Container Access'],['../ax.html#axexternalaccess',1,'External Parameter Access']]],
  ['access_12',['Voxel access',['../python.html#sPyAccessors',1,'']]],
  ['access_20it_20on_20the_20cpu_20and_20gpu_13',['Read a NanoVDB grid and access it on the CPU and GPU',['../NanoVDB_HelloWorld.html#autotoc_md10',1,'']]],
  ['access_20methods_20on_20the_20grid_14',['Why are there no coordinate-based access methods on the grid?',['../faq.html#sAccessor',1,'']]],
  ['accessor_15',['Value Accessor',['../overview.html#subsecValueAccessor',1,'']]],
  ['accessors_16',['Convert an OpenVDB grid to NanoVDB and use accessors',['../NanoVDB_HelloWorld.html#autotoc_md8',1,'']]],
  ['active_20and_20inactive_20values_17',['What are active and inactive values?',['../faq.html#sState',1,'']]],
  ['active_20and_20inactive_20voxels_18',['Active and Inactive Voxels',['../overview.html#subsecInactive',1,'']]],
  ['active_20values_19',['Active Values',['../points.html#secPtActiveValues',1,'']]],
  ['adaptive_20grid_20',['Is OpenVDB an adaptive grid?',['../faq.html#sAdaptiveGrid',1,'']]],
  ['adding_20metadata_21',['Adding metadata',['../codeExamples.html#sAddingMetadata',1,'']]],
  ['advecting_20points_22',['Advecting Points',['../codeExamples.html#sPointAdvect',1,'']]],
  ['against_20houdini_23',['Building Against Houdini',['../build.html#buildBuildHou',1,'']]],
  ['against_20houdini_20maya_24',['Building Against Houdini/Maya',['../build.html#buildBuildHouMaya',1,'']]],
  ['against_20maya_25',['Building Against Maya',['../build.html#buildBuildMaya',1,'']]],
  ['agreement_20for_20openvdb_26',['Is there a Contributor License Agreement for OpenVDB?',['../faq.html#sWhatCLA',1,'']]],
  ['along_20with_20openvdb_20core_27',['Third example: build &apos;everything&apos; in NanoVDB along with OpenVDB core',['../NanoVDB_HowToBuild.html#autotoc_md7',1,'']]],
  ['an_20adaptive_20grid_28',['Is OpenVDB an adaptive grid?',['../faq.html#sAdaptiveGrid',1,'']]],
  ['an_20equivalent_20matrix_20representation_29',['An Equivalent Matrix Representation',['../transformsAndMaps.html#sGettingMat4',1,'']]],
  ['an_20openvdb_20grid_20to_20nanovdb_20and_20use_20accessors_30',['Convert an OpenVDB grid to NanoVDB and use accessors',['../NanoVDB_HelloWorld.html#autotoc_md8',1,'']]],
  ['and_20abi_31',['Versioning, API and ABI',['../axcplusplus.html#vdbaxapiabi',1,'']]],
  ['and_20access_20it_20on_20the_20cpu_20and_20gpu_32',['Read a NanoVDB grid and access it on the CPU and GPU',['../NanoVDB_HelloWorld.html#autotoc_md10',1,'']]],
  ['and_20arguments_33',['Local Variables and Arguments',['../codingStyle.html#sLocalVariablesAndArguments',1,'']]],
  ['and_20assigning_20point_20groups_34',['Creating and Assigning Point Groups',['../codeExamples.html#sPointGroups',1,'']]],
  ['and_20background_20values_35',['Tile, Voxel, and Background Values',['../overview.html#subsecValues',1,'']]],
  ['and_20descriptor_36',['AttributeSet and Descriptor',['../points.html#secPtAttributeSet',1,'']]],
  ['and_20filtering_37',['Point Iteration, Groups and Filtering',['../codeExamples.html#sPointIterationFiltering',1,'']]],
  ['and_20gpu_38',['Read a NanoVDB grid and access it on the CPU and GPU',['../NanoVDB_HelloWorld.html#autotoc_md10',1,'']]],
  ['and_20inactive_20values_39',['What are active and inactive values?',['../faq.html#sState',1,'']]],
  ['and_20inactive_20voxels_40',['Active and Inactive Voxels',['../overview.html#subsecInactive',1,'']]],
  ['and_20maps_41',['and Maps',['../transformsAndMaps.html',1,'Transforms and Maps'],['../overview.html#subsecTrans',1,'Transforms and Maps']]],
  ['and_20mathematical_20operations_42',['Maps and Mathematical Operations',['../transformsAndMaps.html#sGradientAndMaps',1,'']]],
  ['and_20modifying_20a_20grid_43',['Reading and modifying a grid',['../codeExamples.html#sModifyingGrids',1,'']]],
  ['and_20openvdb_20core_44',['First example: building NanoVDB and OpenVDB core',['../NanoVDB_HowToBuild.html#autotoc_md5',1,'']]],
  ['and_20parmlist_45',['ParmFactory and ParmList',['../houdini.html#sParmFactory',1,'']]],
  ['and_20structs_46',['Classes and Structs',['../codingStyle.html#sClassConventions',1,'']]],
  ['and_20tile_20values_47',['Background and Tile Values',['../points.html#secPtBackground',1,'']]],
  ['and_20tools_48',['Utilities and Tools',['../overview.html#secToolUtils',1,'']]],
  ['and_20transforms_49',['Coordinate Systems and Transforms',['../overview.html#secSpaceAndTrans',1,'']]],
  ['and_20use_20accessors_50',['Convert an OpenVDB grid to NanoVDB and use accessors',['../NanoVDB_HelloWorld.html#autotoc_md8',1,'']]],
  ['and_20voxels_51',['Sparse Values and Voxels',['../overview.html#secSparsity',1,'']]],
  ['and_20where_20does_20openvdb_20store_20values_52',['How and where does OpenVDB store values?',['../faq.html#sValue',1,'']]],
  ['and_20writing_20a_20grid_53',['Creating and writing a grid',['../codeExamples.html#sAllocatingGrids',1,'']]],
  ['api_20and_20abi_54',['Versioning, API and ABI',['../axcplusplus.html#vdbaxapiabi',1,'']]],
  ['applications_55',['Is OpenVDB primarily for level set applications?',['../faq.html#sLevelSet',1,'']]],
  ['applying_20drag_56',['Applying Drag',['../axexamples.html#axexamplepointdrag',1,'']]],
  ['apt_20get_57',['Using UNIX apt-get',['../dependencies.html#depUsingAptGet',1,'']]],
  ['are_20active_20and_20inactive_20values_58',['What are active and inactive values?',['../faq.html#sState',1,'']]],
  ['are_20there_20no_20coordinate_20based_20access_20methods_20on_20the_20grid_59',['Why are there no coordinate-based access methods on the grid?',['../faq.html#sAccessor',1,'']]],
  ['are_20tiles_60',['What are tiles?',['../faq.html#sTile',1,'']]],
  ['are_20voxels_20represented_20in_20openvdb_61',['How are voxels represented in OpenVDB?',['../faq.html#sVoxel',1,'']]],
  ['arguments_62',['Local Variables and Arguments',['../codingStyle.html#sLocalVariablesAndArguments',1,'']]],
  ['arithmetic_63',['Arithmetic',['../ax.html#axopbinarithmetic',1,'Arithmetic'],['../ax.html#axopunarithmetic',1,'Arithmetic']]],
  ['arrays_64',['Working with NumPy arrays',['../python.html#sPyNumPy',1,'']]],
  ['artifacts_65',['artifacts',['../build.html#troubleshoot4',1,'Detected VCPKG toolchain is using a mismatching triplet for OpenVDB build artifacts'],['../build.html#troubleshoot5',1,'Unexpected value for the Windows CRT with target build artifacts.']]],
  ['asked_20questions_66',['Frequently Asked Questions',['../faq.html',1,'']]],
  ['assigning_20point_20groups_67',['Creating and Assigning Point Groups',['../codeExamples.html#sPointGroups',1,'']]],
  ['assignments_68',['Assignments',['../ax.html#axopassignment',1,'']]],
  ['ast_69',['The AST',['../axcplusplus.html#vdbaxast',1,'']]],
  ['attribute_20access_70',['Attribute Access',['../ax.html#axattribaccess',1,'']]],
  ['attributehandle_71',['AttributeHandle',['../points.html#secPtAttributeHandle',1,'AttributeHandle'],['../points.html#secPtAttributePerformance',1,'TypedAttributeArray vs AttributeHandle']]],
  ['attributes_72',['Attributes',['../points.html#secPtAttributes',1,'Attributes'],['../codeExamples.html#sConstantStride',1,'Constant Stride Attributes'],['../codeExamples.html#sPointsConversion',1,'Converting Point Attributes'],['../codeExamples.html#sPointStride',1,'Strided Point Attributes']]],
  ['attributes_73',['Basic point attributes',['../axexamples.html#axexamplepointbasic',1,'']]],
  ['attributeset_20and_20descriptor_74',['AttributeSet and Descriptor',['../points.html#secPtAttributeSet',1,'']]],
  ['ax_75',['OpenVDB AX',['../openvdbax.html',1,'index']]],
  ['ax_20c_20documentation_76',['AX C++ Documentation',['../axcplusplus.html',1,'openvdbax']]],
  ['ax_20code_20examples_77',['AX Code Examples',['../axexamples.html',1,'AX Code Examples'],['../axexamples.html#axexamplesintro',1,'AX Code Examples']]],
  ['ax_20language_20documentation_78',['AX Language Documentation',['../ax.html',1,'openvdbax']]],
  ['ax_20programs_79',['AX Programs',['../ax.html#axprograms',1,'']]],
  ['ax_20repository_80',['OpenVDB AX Repository',['../axcplusplus.html#vdbaxrepo',1,'']]],
  ['ax_20supported_20functions_81',['AX Supported Functions',['../axfunctionlist.html',1,'openvdbax']]],
  ['ax_20types_82',['OpenVDB / OpenVDB AX Types',['../axcplusplus.html#vdbaxtoaxtypes',1,'']]],
  ['ax_20vex_20support_83',['AX VEX Support',['../ax.html#axvexsupport',1,'']]]
];
